# permissions for end users to view paddles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: paddle-viewer-role
rules:
- apiGroups:
  - elasticserving.paddlepaddle.org
  resources:
  - paddles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - elasticserving.paddlepaddle.org
  resources:
  - paddles/status
  verbs:
  - get
