# permissions for end users to edit paddles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: paddle-editor-role
rules:
- apiGroups:
  - elasticserving.paddlepaddle.org
  resources:
  - paddles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - elasticserving.paddlepaddle.org
  resources:
  - paddles/status
  verbs:
  - get
