apiVersion: v1
kind: Namespace
metadata:
  name: paddleservice-system
---
apiVersion: v1
data:
  ingress: |-
    {
        "ingressGateway" : "istio-ingressgateway",
        "ingressServiceName" : "istio-ingressgateway.istio-system.svc.cluster.local"
    }
  paddleService: |-
    {
        "containerImage": "jinmionhaobaidu/pdservinglac",
        "version": "latest",
        "port": 9292
    }
kind: ConfigMap
metadata:
  name: paddleservice-config
  namespace: paddleservice-system
---
apiVersion: elasticserving.paddlepaddle.org/v1
kind: PaddleService
metadata:
  name: paddleservice-sample
  namespace: paddleservice-system
spec:
  arg: python3 Serving/python/examples/lac/lac_web_service.py lac_model/ lac_workdir
    9292
  deploymentName: paddleservice
  runtimeVersion: paddleserving
  service:
    minScale: 1
