apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio-injection: enabled
  name: paddleservice-system
---
apiVersion: v1
data:
  ingress: |-
    {
        "ingressGateway" : "istio-ingressgateway",
        "ingressServiceName" : "istio-ingressgateway.istio-system.svc.cluster.local"
    }
kind: ConfigMap
metadata:
  name: paddleservice-config
  namespace: paddleservice-system
---
apiVersion: elasticserving.paddlepaddle.org/v1
kind: PaddleService
metadata:
  name: paddleservice-sample
  namespace: paddleservice-system
spec:
  default:
    arg: python3 Serving/python/examples/lac/lac_web_service.py lac_model/ lac_workdir 9292
    containerImage: jinmionhaobaidu/pdservinglac
    port: 9292
    tag: latest
  defaultTag: latest
  deploymentName: paddleservice
  runtimeVersion: paddleserving
  service:
    minScale: 1
