apiVersion: v1
kind: Namespace
metadata:
  name: paddleservice-system
---
apiVersion: v1
data:
  ingress: |-
    {
        "ingressGateway" : "istio-ingressgateway",
        "ingressServiceName" : "istio-ingressgateway.istio-system.svc.cluster.local"
    }
  paddleService: |-
    {
        "containerImage": "hub.baidubce.com/paddlepaddle/serving",
        "version": "latest",
        "port": 9292
    }
kind: ConfigMap
metadata:
  name: paddleservice-config
  namespace: paddleservice-system
---
apiVersion: elasticserving.paddlepaddle.org/v1
kind: PaddleService
metadata:
  name: paddleservice-sample
  namespace: paddleservice-system
spec:
  arg: pip install paddle-serving-server==0.4.0; pip install paddle-serving-client==0.4.0; pip install paddle-serving-app==0.2.0; pip install shapely==1.7.0 -U; yum install git -y; git clone https://github.com/PaddlePaddle/Serving.git; python -m paddle_serving_app.package --get_model lac; tar -xzf lac.tar.gz && python /Serving/python/examples/lac/lac_web_service.py lac_model/ lac_workdir 9292
  deploymentName: paddleservice
  runtimeVersion: paddleserving
  service:
    minScale: 1
