apiVersion: v1
kind: Namespace
metadata:
  name: paddleservice-system
---
apiVersion: v1
data:
  ingress: |-
    {
        "ingressGateway" : "istio-ingressgateway",
        "ingressServiceName" : "istio-ingressgateway.istio-system.svc.cluster.local"
    }
  paddleService: |-
    {
        "containerImage": "registry.baidubce.com/paddlepaddle/serving",
        "version": "0.6.2-devel",
        "port": 9292
    }
kind: ConfigMap
metadata:
  name: paddleservice-config
  namespace: paddleservice-system
---
apiVersion: elasticserving.paddlepaddle.org/v1
kind: PaddleService
metadata:
  name: paddleservice-sample
  namespace: paddleservice-system
spec:
  arg: git clone https://github.com/PaddlePaddle/Serving; cd Serving; git checkout
    v0.6.2; pip3 install -r python/requirements.txt; pip3 install paddle-serving-client==0.6.2;
    pip3 install paddle-serving-server==0.6.2; pip3 install paddle-serving-app==0.6.2;
    cd examples/lac; python3 -m paddle_serving_app.package --get_model lac; tar -xzf
    lac.tar.gz && python3 lac_web_service.py lac_model/ lac_workdir 9292
  deploymentName: paddleservice
  runtimeVersion: paddleserving
  service:
    minScale: 1
